- name: "Configure zone files"
  tags: dns-zone
  include_tasks: zone.yml

- name: "Configure named"
  tags: dns-config
  include_tasks: config.yml

- name: "Configure localhost resolver"
  tags: dns-localhost
  include_tasks: localhost.yml

