- name: "Install required software"
  tags: install
  include_tasks: install.yml

- name: "Configure firewall"
  tags: firewall
  include_tasks: firewall.yml

- name: "Configure zone files"
  tags: zone
  include_tasks: zone.yml

- name: "Configure named"
  tags: config
  include_tasks: config.yml

- name: "Configure localhost resolver"
  tags: localhost
  include_tasks: localhost.yml
