network: "{{ ansible_facts['default_ipv4']['network'] }}/{{ ansible_facts['default_ipv4']['netmask'] }}"
domains:
- example.com
views:
- name: internal
  match_clients: 
  - "localhost"
  recursion: "yes"
- name: public
  match_clients: 
  - "any"
  recursion: "no"
forwarders:
- 8.8.8.8 # google
named_conf:
- { regex: "listen-on port", line: "\tlisten-on port 53 { localnets; };" }
- { regex: "allow-query", line: "\tallow-query { any; };" }
- { regex: "dnssec-validation", line: "\tdnssec-validation no;" }
- { regex: "include \"/etc/named.rfc", line: "include \"/etc/named/view.{{ views[0]['name'] }}\";" }
resolv_conf:
- { insertbefore: "nameserver {{ forwarders[0] }}", regex: "^$", line: "nameserver 127.0.0.1" }
- { insertbefore: "search", regex: "search", line: "search {{ domains | join(' ') }}" }
