network: "{{ ansible_facts['default_ipv4']['network'] }}/{{ ansible_facts['default_ipv4']['netmask'] }}"
domains:
- example.com
views:
- name: internal
  match-clients: 
  - "localhost"
  recursion: "yes"
- name: public
  match-clients: 
  - "any"
  recursion: "no"
forwarders:
- 8.8.8.8 # google
named_conf:
- { regex: "listen-on port", line: "\tlisten-on port 53 { localnets; };" }
- { regex: "allow-query", line: "\tallow-query { any; };" }
- { regex: "dnssec-validation", line: "\tdnssec-validation no;" }
- { regex: "include \"/etc/named.rfc", line: "include \"/etc/named/view.{{ views[0]['name'] }}\";" }
ifcfg_interface:
- { regex: "DNS[0-9]+=-", line: "DNS1=127.0.0.1" }
- { regex: "DOMAIN=", line: "DOMAIN=\"{{ domains | join(' ') }}\"" }
resolv_conf:
- { state: "absent", regex: "nameserver", line: "There can be only one!" }
- { state: "present", regex: "nameserver", line: "nameserver 127.0.0.1" }
- { state: "present", regex: "search", line: "search {{ domains | join(' ') }}" }
